GET  http://localhost:3000/api/Posts http/1.1

###

POST  http://localhost:3000/api/Posts http/1.1
Content-type: application/json

{
    "titulo": "locura unica",
    "descripcion": "es la primera locura de ese tipo",
    "fechaCreacion": "2022-10-23 10:13:50 ",
    "categoria":"ficción",
    "idAutorPertenece":"1"
}


###
// prueba validación.

POST  http://localhost:3000/api/Posts http/1.1
Content-type: application/json

{
  
    "descripcion": "es la primera locura de ese tipo",
    "fechaCreacion": "2022-10-23 10:13:50 ",
    "categoria":"ficción",
    "idAutorPertenece":"1"
}
###

PUT http://localhost:3000/api/Posts http/1.1
Content-type: application/json

{
    "titulo": "locura unica",
    "descripcion": "primera modificacion de ese tipo",
    "fechaCreacion": "2022-10-23 10:13:50 ",
    "categoria":"ficción",
    "idAutorPertenece":"1"
}


###
// prueba validacion
PUT http://localhost:3000/api/Posts http/1.1
Content-type: application/json

{
    "titulo": "locura unica",
    "descripcion": "primera modificacion de ese tipo",
    "fechaCreacion": "2022-10-23 10:13:50 ",
   
    "idAutorPertenece":"1"
}
###

DELETE  http://localhost:3000/api/Posts http/1.1
Content-type: application/json

{
    "titulo": "locura unica",
    "descripcion": "primera modificacion de ese tipo",
    "fechaCreacion": "2022-10-23 10:13:50 ",
    "categoria":"ficción",
    "idAutorPertenece":"1"
}

###
//prueba validacion
DELETE  http://localhost:3000/api/Posts http/1.1
Content-type: application/json

{
    "titulo": "locura unica",
    "descripcion": "primera modificacion de ese tipo",
    "fechaCreacion": "2022-10-23 10:13:50 "
    
}
###


GET  http://localhost:3000/api/Authors http/1.1

###

POST http://localhost:3000/api/Authors
Content-Type: application/json

{"nombre":"gerardo", "email":"g@gmail.com"}
    
###
//provando validaciones
POST http://localhost:3000/api/Authors
Content-Type: application/json

{"nombre":"gerardo" }

###

PUT http://localhost:3000/api/Authors http/1.1
Content-type: application/json

{"nombre":"gerardo", 
"email":"g@gmail.com",
"imagen": "hdfl"
}

###
// prueba validacion
PUT http://localhost:3000/api/Authors http/1.1
Content-type: application/json

{"nombre":"gerardo", 
"email":"g@gmail.com"

}
###

DELETE  http://localhost:3000/api/Authors http/1.1
Content-type: application/json

{"nombre":"gerardo", 
"email":"g@gmail.com",
"imagen": "kdjflshdfl"
}

###
// probando validacion
DELETE  http://localhost:3000/api/Authors http/1.1
Content-type: application/json

{"nombre":"gerardo", 
"imagen": "kdjflshdfl"
}

